id: PF0542CFB
initial_creation_type: input
source_metadata:
  title: Pratītyasamutpādahṛdayavyākhyāna
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Philosophy -- Buddhist
  data entry: members of the Digital Sanskrit Buddhist Canon Input Project
  contribution to GRETIL: members of the Digital Sanskrit Buddhist Canon Input Project
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T15:18:58.918449'
last_modified_at: '2022-03-09T15:18:58.918461'
